import { loadEnvFile } from 'node:process';
import { existsSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { resolve } from 'node:path';
import { readConfig } from './config.js';
import { Vault } from './crypto.js';
import { Store } from './store.js';
import { DiscordHttpApi } from './discord.js';
import { buildApp } from './app.js';
import { createBot } from './bot/gateway.js';
import { InboxStore } from './inbox/store.js';
import { InboxService } from './inbox/service.js';
import { createInboxTransport,attachInboxGateway } from './inbox/gateway.js';
import { EventStore } from './events/store.js';
import { EventService } from './events/service.js';
import { createEventTransport } from './events/discord.js';
import { TutorialStore } from './tutorial/store.js';
import { TutorialService } from './tutorial/service.js';
import { createTutorialTransport } from './tutorial/discord.js';
import { attachTutorialGateway } from './tutorial/gateway.js';
import {InstagramSettingsStore,InstagramSettingsService} from './instagram/settings.js';
import {createInstagramSettingsTransport} from './instagram/discord.js';
import {InstagramDeliveryStore} from './instagram/deliveries.js';
import {createInstagramPostingTransport} from './instagram/posting.js';
import {InstagramPostingService} from './instagram/service.js';
import {attachInstagramGateway} from './instagram/gateway.js';

process.umask(0o077);
if (existsSync('.env')) loadEnvFile('.env');
const config=readConfig();
// With no credentials the public setup page is available, but no login/session can be created.
const key=config.configured ? config.DATA_ENCRYPTION_KEY : randomBytes(32).toString('base64');
const vault=new Vault(key);
const store=new Store(config.configured ? resolve(config.DATA_DIR,'discord-bot.sqlite') : ':memory:',vault);
const inboxStore=new InboxStore(store.db,vault);
const eventStore=new EventStore(store.db,vault);
const tutorialStore=new TutorialStore(store.db,vault,(...args)=>store.addActivity(...args));
const instagramStore=new InstagramSettingsStore(store.db,vault,(...args)=>store.addActivity(...args));
const instagramDeliveries=new InstagramDeliveryStore(store.db,vault);
instagramDeliveries.prune();instagramDeliveries.recover();
eventStore.prune();eventStore.recover();
store.prune();
store.recoverPendingDeliveries();
inboxStore.prune();inboxStore.recoverPendingReplies();
const bot=createBot(config,{addActivity:(...args)=>store.addActivity(...args),removeGuild:id=>{instagramDeliveries.removeGuild(id);instagramStore.removeGuild(id);tutorialStore.removeGuild(id);eventStore.removeGuild(id);inboxStore.removeGuild(id);store.removeGuild(id);}});
const inbox=new InboxService(inboxStore,createInboxTransport(bot.client),(...args)=>store.addActivity(...args));
const inboxGateway=attachInboxGateway(bot.client,inbox);
const events=new EventService(eventStore,createEventTransport(bot.client),(...args)=>store.addActivity(...args));
const tutorials=new TutorialService(tutorialStore,createTutorialTransport(bot.client));
const tutorialGateway=attachTutorialGateway(bot.client,tutorials);
const instagramTransport=createInstagramPostingTransport(bot.client);
const instagram=new InstagramSettingsService(instagramStore,createInstagramSettingsTransport(bot.client),config.INSTAGRAM_LINKS_ENABLED,instagramTransport);
const instagramPosting=new InstagramPostingService(instagramStore,instagramDeliveries,instagramTransport,config.INSTAGRAM_LINKS_ENABLED,(...args)=>store.addActivity(...args));
const instagramGateway=attachInstagramGateway(bot.client,instagramPosting,config.INSTAGRAM_LINKS_ENABLED);
const app=await buildApp(config,store,new DiscordHttpApi(config),bot,inbox,events,tutorials,instagram,instagramDeliveries);
const cleanup=setInterval(()=>{try {instagramDeliveries.prune();eventStore.prune();inboxStore.prune();store.prune();} catch {console.error('Scheduled data cleanup failed. Check storage and disk space.');}},60*60_000);
cleanup.unref();
let stopping=false;
async function shutdown() {
  if (stopping) return; stopping=true;
  clearInterval(cleanup);
  instagramGateway.stop();
  const instagramStopped=instagramPosting.stop();
  await app.close(); tutorialGateway.stop(); inboxGateway.stop(); await instagramStopped; await bot.stop(); store.close();
}
process.once('SIGINT',()=>void shutdown()); process.once('SIGTERM',()=>void shutdown());
await app.listen({host:config.HOST,port:config.PORT});
void bot.start().catch(()=>console.error('Discord bot could not connect. Check its configuration; no credentials are written to logs.'));
console.log(`Discord Bot listening locally on ${config.HOST}:${config.PORT}. ${config.configured ? 'Discord sign-in configured.' : 'Setup required; sign-in disabled.'}`);
