import { ArrowLeft, ExternalLink } from 'lucide-react';

export function Information({ page }: { page: 'setup' | 'accessibility' | 'privacy' }) {
  return <article className="document-page"><a className="back-link" href="#overview"><ArrowLeft size={18} aria-hidden="true" />Back to overview</a>
    {page === 'setup' ? <>
      <h1>Set up your Discord application</h1><p className="document-intro">Connect your management website and staff inbox to Discord. Keep your application secrets on the computer running the bot.</p>
      <section><h2>1. Create your application</h2><p>Open the <a href="https://discord.com/developers/applications" target="_blank" rel="noreferrer">Discord Developer Portal<ExternalLink className="inline-icon" size={14} aria-hidden="true" /><span className="sr-only"> (opens in a new tab)</span></a>, choose <strong>New Application</strong>, and give your bot a name. In your application’s <strong>Bot</strong> page, create or reset its token when you are ready to configure it. Treat the token like a password.</p></section>
      <section><h2>2. Fill in the configuration placeholders</h2><p>Make a private copy of the project’s <code>.env.example</code> file named <code>.env</code>. Follow its comments to enter the application ID, OAuth client secret, bot token, website address, and locally generated security secrets. Use the exact variable names supplied in that file.</p><p>The application ID is available under <strong>General Information</strong>, the OAuth secret under <strong>OAuth2</strong>, and the bot token under <strong>Bot</strong>. Never paste these values into Discord, a website form, an issue, or a GitHub commit. The template contains placeholders only.</p><p>Keep a protected recovery copy of the encryption key separately from your database. Losing or replacing the key makes saved staff messages unreadable.</p></section>
      <section><h2>3. Register the sign-in redirect</h2><p>In the Developer Portal’s <strong>OAuth2 → Redirects</strong>, add your configured website address followed by <code>/auth/callback</code>. It must exactly match the address configured for this installation. Use HTTPS for public access. Local development uses the address documented in the project README.</p><p>Save the changes, then install your application’s bot into your server using the installation settings in the Developer Portal. The bot must belong to the server so this website can verify current membership and roles.</p></section>
      <section><h2>4. Start the service and sign in</h2><p>Follow the current repository README to build and start the service. Return to Overview and choose <strong>Continue with Discord</strong>. Sign in with an account that owns the server or has Discord’s <strong>Administrator</strong> permission. Select a server, then review its website permissions.</p><p>Sign in as the server owner for the first permission setup. The owner can delegate <strong>Manage lower roles</strong> to eligible administrator roles.</p></section>
      <section><h2>5. Enable the staff inbox</h2><p>Open <strong>Staff inbox</strong> for the selected server, read the retention notice, and enable member contact when your staff are ready. Members can then use <code>/contact</code> in that server or choose the server when they DM the bot. A first DM without a selected server is not saved or forwarded; the bot asks the member to select a destination and resend it.</p><p>Grant <strong>Read staff inbox</strong> to administrators who should see conversations, and also <strong>Reply to members</strong> to those who should reply or close conversations. The <strong>Manage settings</strong> permission controls whether the inbox is enabled. The server owner already has full access.</p></section>
      <section><h2>Raspberry Pi installation guide</h2><p>This is the application connection guide for the current development stage. The detailed, illustrated Raspberry Pi 3 B+ installation PDF will be prepared after the bot features and final deployment setup are complete.</p><p>Do not expose this development setup directly to the internet. The final deployment stage will configure the public address, HTTPS, secure access, backups, and Pi service settings.</p></section>
    </> : page === 'accessibility' ? <>
      <h1>Accessibility statement</h1><p className="document-intro">This dashboard is designed to help administrators manage their community using a keyboard, assistive technology, or a small screen.</p>
      <section><h2>What is included</h2><ul><li>Semantic headings, named navigation, and a skip-to-content link.</li><li>Visible keyboard focus, labeled form controls, and text alongside meaningful actions.</li><li>Screen-reader announcements for loading, errors, and saved changes.</li><li>Responsive layouts, scalable text, and support for reduced-motion preferences.</li><li>A first-login tutorial with Back, Skip, and a reset option.</li></ul></section>
      <section><h2>Accessibility target and limitations</h2><p>The target is WCAG 2.2 Level AA. This is an early development stage, and full conformance has not been independently audited. Some flows depend on Discord’s sign-in pages, whose accessibility is controlled by Discord.</p><p>Content such as administrator-authored tutorials and event graphics needs accessible text from its authors. Accessibility checks will continue as those features are built.</p></section>
      <section><h2>Report an accessibility problem</h2><p>Contact your server owner or an administrator through your usual Discord channel. Include the page, what you were trying to do, and any browser or assistive technology details you are comfortable sharing. Do not share tokens, passwords, or private member messages.</p></section>
    </> : <>
      <h1>Privacy &amp; retention</h1><p className="document-intro">Each server has a separate administrative workspace. Website access requires Discord sign-in and verified Administrator permission, with a server-owner exception.</p>
      <section><h2>What this service uses</h2><p>The service uses your Discord identity, current server membership, and roles to decide what you can access. It stores website sessions, per-server role permission settings, tutorial progress, and administration activity needed for the dashboard.</p><p>Login cookies are used to keep you signed in. This website does not include advertising or third-party analytics. Discord handles its own sign-in page and privacy practices.</p></section>
      <section><h2>Staff messages and retention</h2><p>Staff DMs are disabled until an authorized administrator enables them for a server. Members choose the server whose staff will receive their messages. A first DM without a selected destination is not saved or forwarded; the bot asks the member to choose a server and resend it.</p><p>The inbox stores encrypted DM text and attachment details for 90 days, with participant identifiers, timestamps, and delivery status. Messages that reach 90 days are hidden from the website and removed during scheduled cleanup. Only authorized administrators in the selected server can read the conversations through this website. Replies also require permission to reply to members.</p><p>Attachments are saved as links to Discord. The bot does not download the files, and those links may expire before the conversation does. Disabling the inbox stops new messages and replies while keeping retained history available to authorized staff. Cleanup does not delete copies held in Discord or the host’s backups.</p></section>
      <section><h2>Channel messages and future exports</h2><p>The channel composer handles your message text temporarily to send it to Discord. Its delivery records and administration activity do not contain message text. This stage does not collect messages from server channels or provide message exports. A server-channel message audit and permission-controlled export are planned for a later stage.</p><p>When exports are added, downloaded copies will be controlled by the administrator who exports them. Server administrators will need their own secure storage and deletion process for those copies.</p></section>
      <section><h2>Event requests and graphics</h2><p>Event details and announcement delivery records are retained locally for 90 days, with sensitive draft text encrypted. Graphic uploads are sent to Discord and are not kept in the local database. The announcement uses the Discord event cover image. Local cleanup does not delete the event or its announcement from Discord.</p></section>
      <section><h2>Server access and accountability</h2><p>Roles define website permissions within each server; a grant cannot bypass the Discord Administrator requirement. The server owner retains full website access. Permission changes are recorded as administration activity without member message content.</p><p>The person hosting this bot controls its local database, backups, and installation. Contact that person or your server owner for questions about your data or requests to remove it.</p></section>
    </>}
  </article>;
}
